feat: Add the cmdserver package to handle Diatheke command webhooks.
cobaltspeech/examples-go pull request #8
Opened 2021-09-17 22:31 UTC by mplooster

This example package contains classes to allow users to experiment
with using webhooks for command fulfillment, provided the Diatheke
model is set up to handle commands this way. See the READMEs for
details on how to use the package.

2021-09-17 22:34 UTC, cobaltjenkins commented
# Test Report: 
```
cd cmdserver && go test -cover -race ./...
ok  	github.com/cobaltspeech/examples-go/cmdserver	0.035s	coverage: 58.7% of statements

```

2021-09-18 00:43 UTC, kapitoshka438 requested changes
LGTM. There is just a typo.

2021-09-18 00:43 UTC, kapitoshka438 commented on cmdserver/README.md
> +	// Do something interseting with the command input.
```suggestion
	// Do something interesting with the command input.
```

2021-09-18 02:37 UTC, mplooster commented on cmdserver/README.md
> +	// Do something interseting with the command input.
Good catch! I've fixed it.

2021-09-18 02:40 UTC, cobaltjenkins commented
# Test Report: 
```
cd cmdserver && go test -cover -race ./...
ok  	github.com/cobaltspeech/examples-go/cmdserver	0.034s	coverage: 58.7% of statements

```

2021-09-18 07:27 UTC, happyalu approved these changes
lgtm

2021-09-18 07:27 UTC, happyalu commented on cmdserver/params.go
> +// Params is an alias for a map[string]string that
these functions are not threadsafe; perhaps that's not a problem here, but worth documenting somewhere just in case someone lifts this for reuse.

2021-09-18 08:53 UTC, kapitoshka438 approved these changes
👍

2021-09-20 20:21 UTC, cobaltjenkins commented
# Test Report: 
```
cd cmdserver && go test -cover -race ./...
ok  	github.com/cobaltspeech/examples-go/cmdserver	0.035s	coverage: 58.7% of statements

```

2021-09-20 21:13 UTC, merged